/* history.c generated by valac 0.22.1, the Vala compiler
 * generated from history.vala, do not modify */

/*
 * Copyright (C) 2011-2012 Robert Ancell
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 2 of the License, or (at your option) any later
 * version. See http://www.gnu.org/copyleft/gpl.html the full text of the
 * license.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>


#define TYPE_HISTORY (history_get_type ())
#define HISTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_HISTORY, History))
#define HISTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_HISTORY, HistoryClass))
#define IS_HISTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_HISTORY))
#define IS_HISTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_HISTORY))
#define HISTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_HISTORY, HistoryClass))

typedef struct _History History;
typedef struct _HistoryClass HistoryClass;
typedef struct _HistoryPrivate HistoryPrivate;

#define TYPE_HISTORY_ENTRY (history_entry_get_type ())
#define HISTORY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_HISTORY_ENTRY, HistoryEntry))
#define HISTORY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_HISTORY_ENTRY, HistoryEntryClass))
#define IS_HISTORY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_HISTORY_ENTRY))
#define IS_HISTORY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_HISTORY_ENTRY))
#define HISTORY_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_HISTORY_ENTRY, HistoryEntryClass))

typedef struct _HistoryEntry HistoryEntry;
typedef struct _HistoryEntryClass HistoryEntryClass;

#define TYPE_STAT_ENTRY (stat_entry_get_type ())
#define STAT_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_STAT_ENTRY, StatEntry))
#define STAT_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_STAT_ENTRY, StatEntryClass))
#define IS_STAT_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_STAT_ENTRY))
#define IS_STAT_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_STAT_ENTRY))
#define STAT_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_STAT_ENTRY, StatEntryClass))

typedef struct _StatEntry StatEntry;
typedef struct _StatEntryClass StatEntryClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define __g_list_free__history_entry_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__history_entry_unref0_ (var), NULL)))
#define __g_list_free__stat_entry_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__stat_entry_unref0_ (var), NULL)))
typedef struct _StatEntryPrivate StatEntryPrivate;
#define _stat_entry_unref0(var) ((var == NULL) ? NULL : (var = (stat_entry_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _history_entry_unref0(var) ((var == NULL) ? NULL : (var = (history_entry_unref (var), NULL)))
typedef struct _HistoryEntryPrivate HistoryEntryPrivate;
#define _g_time_zone_unref0(var) ((var == NULL) ? NULL : (var = (g_time_zone_unref (var), NULL)))
typedef struct _ParamSpecHistory ParamSpecHistory;
typedef struct _ParamSpecHistoryEntry ParamSpecHistoryEntry;
typedef struct _ParamSpecStatEntry ParamSpecStatEntry;

struct _History {
	GTypeInstance parent_instance;
	volatile int ref_count;
	HistoryPrivate * priv;
	gchar* filename;
	gchar* statFileName;
	GList* entries;
	GList* statEntries;
};

struct _HistoryClass {
	GTypeClass parent_class;
	void (*finalize) (History *self);
};

struct _StatEntry {
	GTypeInstance parent_instance;
	volatile int ref_count;
	StatEntryPrivate * priv;
	guint width;
	guint height;
	guint n_mines;
	guint wins;
	guint loses;
};

struct _StatEntryClass {
	GTypeClass parent_class;
	void (*finalize) (StatEntry *self);
};

struct _HistoryEntry {
	GTypeInstance parent_instance;
	volatile int ref_count;
	HistoryEntryPrivate * priv;
	GDateTime* date;
	guint width;
	guint height;
	guint n_mines;
	guint duration;
};

struct _HistoryEntryClass {
	GTypeClass parent_class;
	void (*finalize) (HistoryEntry *self);
};

struct _ParamSpecHistory {
	GParamSpec parent_instance;
};

struct _ParamSpecHistoryEntry {
	GParamSpec parent_instance;
};

struct _ParamSpecStatEntry {
	GParamSpec parent_instance;
};


static gpointer history_parent_class = NULL;
static gpointer history_entry_parent_class = NULL;
static gpointer stat_entry_parent_class = NULL;

gpointer history_ref (gpointer instance);
void history_unref (gpointer instance);
GParamSpec* param_spec_history (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_history (GValue* value, gpointer v_object);
void value_take_history (GValue* value, gpointer v_object);
gpointer value_get_history (const GValue* value);
GType history_get_type (void) G_GNUC_CONST;
gpointer history_entry_ref (gpointer instance);
void history_entry_unref (gpointer instance);
GParamSpec* param_spec_history_entry (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_history_entry (GValue* value, gpointer v_object);
void value_take_history_entry (GValue* value, gpointer v_object);
gpointer value_get_history_entry (const GValue* value);
GType history_entry_get_type (void) G_GNUC_CONST;
gpointer stat_entry_ref (gpointer instance);
void stat_entry_unref (gpointer instance);
GParamSpec* param_spec_stat_entry (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_stat_entry (GValue* value, gpointer v_object);
void value_take_stat_entry (GValue* value, gpointer v_object);
gpointer value_get_stat_entry (const GValue* value);
GType stat_entry_get_type (void) G_GNUC_CONST;
enum  {
	HISTORY_DUMMY_PROPERTY
};
static void _history_entry_unref0_ (gpointer var);
static void _g_list_free__history_entry_unref0_ (GList* self);
static void _stat_entry_unref0_ (gpointer var);
static void _g_list_free__stat_entry_unref0_ (GList* self);
History* history_new (const gchar* filename, const gchar* statFileName);
History* history_construct (GType object_type, const gchar* filename, const gchar* statFileName);
void history_add (History* self, HistoryEntry* entry);
StatEntry* history_find_stat (History* self, guint width, guint height, guint n_mines);
void history_addWin (History* self, guint width, guint height, guint n_mines);
StatEntry* stat_entry_new (guint width, guint height, guint n_mines, guint wins, guint loses);
StatEntry* stat_entry_construct (GType object_type, guint width, guint height, guint n_mines, guint wins, guint loses);
void history_addLose (History* self, guint width, guint height, guint n_mines);
void history_load (History* self);
static GDateTime* history_parse_date (History* self, const gchar* date);
HistoryEntry* history_entry_new (GDateTime* date, guint width, guint height, guint n_mines, guint duration);
HistoryEntry* history_entry_construct (GType object_type, GDateTime* date, guint width, guint height, guint n_mines, guint duration);
void history_save (History* self);
void history_reset (History* self);
static void g_cclosure_user_marshal_VOID__HISTORY_ENTRY (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void history_finalize (History* obj);
enum  {
	HISTORY_ENTRY_DUMMY_PROPERTY
};
static void history_entry_finalize (HistoryEntry* obj);
enum  {
	STAT_ENTRY_DUMMY_PROPERTY
};
static void stat_entry_finalize (StatEntry* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static void _history_entry_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (history_entry_unref (var), NULL));
}


static void _g_list_free__history_entry_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _history_entry_unref0_, NULL);
	g_list_free (self);
}


static void _stat_entry_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (stat_entry_unref (var), NULL));
}


static void _g_list_free__stat_entry_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _stat_entry_unref0_, NULL);
	g_list_free (self);
}


History* history_construct (GType object_type, const gchar* filename, const gchar* statFileName) {
	History* self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (filename != NULL, NULL);
	g_return_val_if_fail (statFileName != NULL, NULL);
	self = (History*) g_type_create_instance (object_type);
	_tmp0_ = filename;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->filename);
	self->filename = _tmp1_;
	_tmp2_ = statFileName;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (self->statFileName);
	self->statFileName = _tmp3_;
	__g_list_free__history_entry_unref0_0 (self->entries);
	self->entries = NULL;
	__g_list_free__stat_entry_unref0_0 (self->statEntries);
	self->statEntries = NULL;
	return self;
}


History* history_new (const gchar* filename, const gchar* statFileName) {
	return history_construct (TYPE_HISTORY, filename, statFileName);
}


static gpointer _history_entry_ref0 (gpointer self) {
	return self ? history_entry_ref (self) : NULL;
}


void history_add (History* self, HistoryEntry* entry) {
	HistoryEntry* _tmp0_ = NULL;
	HistoryEntry* _tmp1_ = NULL;
	HistoryEntry* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (entry != NULL);
	_tmp0_ = entry;
	_tmp1_ = _history_entry_ref0 (_tmp0_);
	self->entries = g_list_append (self->entries, _tmp1_);
	_tmp2_ = entry;
	g_signal_emit_by_name (self, "entry-added", _tmp2_);
}


static gpointer _stat_entry_ref0 (gpointer self) {
	return self ? stat_entry_ref (self) : NULL;
}


StatEntry* history_find_stat (History* self, guint width, guint height, guint n_mines) {
	StatEntry* result = NULL;
	GList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->statEntries;
	{
		GList* stat_collection = NULL;
		GList* stat_it = NULL;
		stat_collection = _tmp0_;
		for (stat_it = stat_collection; stat_it != NULL; stat_it = stat_it->next) {
			StatEntry* _tmp1_ = NULL;
			StatEntry* stat = NULL;
			_tmp1_ = _stat_entry_ref0 ((StatEntry*) stat_it->data);
			stat = _tmp1_;
			{
				gboolean _tmp2_ = FALSE;
				gboolean _tmp3_ = FALSE;
				StatEntry* _tmp4_ = NULL;
				guint _tmp5_ = 0U;
				guint _tmp6_ = 0U;
				gboolean _tmp10_ = FALSE;
				gboolean _tmp14_ = FALSE;
				_tmp4_ = stat;
				_tmp5_ = _tmp4_->width;
				_tmp6_ = width;
				if (_tmp5_ == _tmp6_) {
					StatEntry* _tmp7_ = NULL;
					guint _tmp8_ = 0U;
					guint _tmp9_ = 0U;
					_tmp7_ = stat;
					_tmp8_ = _tmp7_->height;
					_tmp9_ = height;
					_tmp3_ = _tmp8_ == _tmp9_;
				} else {
					_tmp3_ = FALSE;
				}
				_tmp10_ = _tmp3_;
				if (_tmp10_) {
					StatEntry* _tmp11_ = NULL;
					guint _tmp12_ = 0U;
					guint _tmp13_ = 0U;
					_tmp11_ = stat;
					_tmp12_ = _tmp11_->n_mines;
					_tmp13_ = n_mines;
					_tmp2_ = _tmp12_ == _tmp13_;
				} else {
					_tmp2_ = FALSE;
				}
				_tmp14_ = _tmp2_;
				if (_tmp14_) {
					result = stat;
					return result;
				}
				_stat_entry_unref0 (stat);
			}
		}
	}
	result = NULL;
	return result;
}


void history_addWin (History* self, guint width, guint height, guint n_mines) {
	StatEntry* stat = NULL;
	guint _tmp0_ = 0U;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
	StatEntry* _tmp3_ = NULL;
	StatEntry* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = width;
	_tmp1_ = height;
	_tmp2_ = n_mines;
	_tmp3_ = history_find_stat (self, _tmp0_, _tmp1_, _tmp2_);
	stat = _tmp3_;
	_tmp4_ = stat;
	if (_tmp4_ != NULL) {
		StatEntry* _tmp5_ = NULL;
		guint _tmp6_ = 0U;
		_tmp5_ = stat;
		_tmp6_ = _tmp5_->wins;
		_tmp5_->wins = _tmp6_ + 1;
	} else {
		guint _tmp7_ = 0U;
		guint _tmp8_ = 0U;
		guint _tmp9_ = 0U;
		StatEntry* _tmp10_ = NULL;
		_tmp7_ = width;
		_tmp8_ = height;
		_tmp9_ = n_mines;
		_tmp10_ = stat_entry_new (_tmp7_, _tmp8_, _tmp9_, (guint) 1, (guint) 0);
		self->statEntries = g_list_append (self->statEntries, _tmp10_);
	}
	_stat_entry_unref0 (stat);
}


void history_addLose (History* self, guint width, guint height, guint n_mines) {
	StatEntry* stat = NULL;
	guint _tmp0_ = 0U;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
	StatEntry* _tmp3_ = NULL;
	StatEntry* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = width;
	_tmp1_ = height;
	_tmp2_ = n_mines;
	_tmp3_ = history_find_stat (self, _tmp0_, _tmp1_, _tmp2_);
	stat = _tmp3_;
	_tmp4_ = stat;
	if (_tmp4_ != NULL) {
		StatEntry* _tmp5_ = NULL;
		guint _tmp6_ = 0U;
		_tmp5_ = stat;
		_tmp6_ = _tmp5_->loses;
		_tmp5_->loses = _tmp6_ + 1;
	} else {
		guint _tmp7_ = 0U;
		guint _tmp8_ = 0U;
		guint _tmp9_ = 0U;
		StatEntry* _tmp10_ = NULL;
		_tmp7_ = width;
		_tmp8_ = height;
		_tmp9_ = n_mines;
		_tmp10_ = stat_entry_new (_tmp7_, _tmp8_, _tmp9_, (guint) 0, (guint) 1);
		self->statEntries = g_list_append (self->statEntries, _tmp10_);
	}
	_stat_entry_unref0 (stat);
}


void history_load (History* self) {
	gchar* contents = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp6_ = NULL;
	gchar** _tmp7_ = NULL;
	gchar** _tmp8_ = NULL;
	gchar* _tmp37_ = NULL;
	const gchar* _tmp43_ = NULL;
	gchar** _tmp44_ = NULL;
	gchar** _tmp45_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	__g_list_free__history_entry_unref0_0 (self->entries);
	self->entries = NULL;
	_tmp0_ = g_strdup ("");
	contents = _tmp0_;
	{
		const gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		_tmp1_ = self->filename;
		g_file_get_contents (_tmp1_, &_tmp2_, NULL, &_inner_error_);
		_g_free0 (contents);
		contents = _tmp2_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_FILE_ERROR) {
				goto __catch2_g_file_error;
			}
			_g_free0 (contents);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally2;
	__catch2_g_file_error:
	{
		GError* e = NULL;
		GError* _tmp3_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp3_ = e;
		if (!g_error_matches (_tmp3_, G_FILE_ERROR, G_FILE_ERROR_NOENT)) {
			GError* _tmp4_ = NULL;
			const gchar* _tmp5_ = NULL;
			_tmp4_ = e;
			_tmp5_ = _tmp4_->message;
			g_warning ("history.vala:80: Failed to load history: %s", _tmp5_);
		}
		_g_error_free0 (e);
		_g_free0 (contents);
		return;
	}
	__finally2:
	if (_inner_error_ != NULL) {
		_g_free0 (contents);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp6_ = contents;
	_tmp8_ = _tmp7_ = g_strsplit (_tmp6_, "\n", 0);
	{
		gchar** line_collection = NULL;
		gint line_collection_length1 = 0;
		gint _line_collection_size_ = 0;
		gint line_it = 0;
		line_collection = _tmp8_;
		line_collection_length1 = _vala_array_length (_tmp7_);
		for (line_it = 0; line_it < _vala_array_length (_tmp7_); line_it = line_it + 1) {
			gchar* _tmp9_ = NULL;
			gchar* line = NULL;
			_tmp9_ = g_strdup (line_collection[line_it]);
			line = _tmp9_;
			{
				gchar** tokens = NULL;
				const gchar* _tmp10_ = NULL;
				gchar** _tmp11_ = NULL;
				gchar** _tmp12_ = NULL;
				gint tokens_length1 = 0;
				gint _tokens_size_ = 0;
				gchar** _tmp13_ = NULL;
				gint _tmp13__length1 = 0;
				GDateTime* date = NULL;
				gchar** _tmp14_ = NULL;
				gint _tmp14__length1 = 0;
				const gchar* _tmp15_ = NULL;
				GDateTime* _tmp16_ = NULL;
				GDateTime* _tmp17_ = NULL;
				gint width = 0;
				gchar** _tmp18_ = NULL;
				gint _tmp18__length1 = 0;
				const gchar* _tmp19_ = NULL;
				gint _tmp20_ = 0;
				gint height = 0;
				gchar** _tmp21_ = NULL;
				gint _tmp21__length1 = 0;
				const gchar* _tmp22_ = NULL;
				gint _tmp23_ = 0;
				gint n_mines = 0;
				gchar** _tmp24_ = NULL;
				gint _tmp24__length1 = 0;
				const gchar* _tmp25_ = NULL;
				gint _tmp26_ = 0;
				gint duration = 0;
				gchar** _tmp27_ = NULL;
				gint _tmp27__length1 = 0;
				const gchar* _tmp28_ = NULL;
				gint _tmp29_ = 0;
				GDateTime* _tmp30_ = NULL;
				gint _tmp31_ = 0;
				gint _tmp32_ = 0;
				gint _tmp33_ = 0;
				gint _tmp34_ = 0;
				HistoryEntry* _tmp35_ = NULL;
				HistoryEntry* _tmp36_ = NULL;
				_tmp10_ = line;
				_tmp12_ = _tmp11_ = g_strsplit (_tmp10_, " ", 0);
				tokens = _tmp12_;
				tokens_length1 = _vala_array_length (_tmp11_);
				_tokens_size_ = tokens_length1;
				_tmp13_ = tokens;
				_tmp13__length1 = tokens_length1;
				if (_tmp13__length1 != 5) {
					tokens = (_vala_array_free (tokens, tokens_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (line);
					continue;
				}
				_tmp14_ = tokens;
				_tmp14__length1 = tokens_length1;
				_tmp15_ = _tmp14_[0];
				_tmp16_ = history_parse_date (self, _tmp15_);
				date = _tmp16_;
				_tmp17_ = date;
				if (_tmp17_ == NULL) {
					_g_date_time_unref0 (date);
					tokens = (_vala_array_free (tokens, tokens_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (line);
					continue;
				}
				_tmp18_ = tokens;
				_tmp18__length1 = tokens_length1;
				_tmp19_ = _tmp18_[1];
				_tmp20_ = atoi (_tmp19_);
				width = _tmp20_;
				_tmp21_ = tokens;
				_tmp21__length1 = tokens_length1;
				_tmp22_ = _tmp21_[2];
				_tmp23_ = atoi (_tmp22_);
				height = _tmp23_;
				_tmp24_ = tokens;
				_tmp24__length1 = tokens_length1;
				_tmp25_ = _tmp24_[3];
				_tmp26_ = atoi (_tmp25_);
				n_mines = _tmp26_;
				_tmp27_ = tokens;
				_tmp27__length1 = tokens_length1;
				_tmp28_ = _tmp27_[4];
				_tmp29_ = atoi (_tmp28_);
				duration = _tmp29_;
				_tmp30_ = date;
				_tmp31_ = width;
				_tmp32_ = height;
				_tmp33_ = n_mines;
				_tmp34_ = duration;
				_tmp35_ = history_entry_new (_tmp30_, (guint) _tmp31_, (guint) _tmp32_, (guint) _tmp33_, (guint) _tmp34_);
				_tmp36_ = _tmp35_;
				history_add (self, _tmp36_);
				_history_entry_unref0 (_tmp36_);
				_g_date_time_unref0 (date);
				tokens = (_vala_array_free (tokens, tokens_length1, (GDestroyNotify) g_free), NULL);
				_g_free0 (line);
			}
		}
		line_collection = (_vala_array_free (line_collection, line_collection_length1, (GDestroyNotify) g_free), NULL);
	}
	__g_list_free__stat_entry_unref0_0 (self->statEntries);
	self->statEntries = NULL;
	_tmp37_ = g_strdup ("");
	_g_free0 (contents);
	contents = _tmp37_;
	{
		const gchar* _tmp38_ = NULL;
		gchar* _tmp39_ = NULL;
		_tmp38_ = self->statFileName;
		g_file_get_contents (_tmp38_, &_tmp39_, NULL, &_inner_error_);
		_g_free0 (contents);
		contents = _tmp39_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_FILE_ERROR) {
				goto __catch3_g_file_error;
			}
			_g_free0 (contents);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally3;
	__catch3_g_file_error:
	{
		GError* e = NULL;
		GError* _tmp40_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp40_ = e;
		if (!g_error_matches (_tmp40_, G_FILE_ERROR, G_FILE_ERROR_NOENT)) {
			GError* _tmp41_ = NULL;
			const gchar* _tmp42_ = NULL;
			_tmp41_ = e;
			_tmp42_ = _tmp41_->message;
			g_warning ("history.vala:111: Failed to load statistic: %s", _tmp42_);
		}
		_g_error_free0 (e);
		_g_free0 (contents);
		return;
	}
	__finally3:
	if (_inner_error_ != NULL) {
		_g_free0 (contents);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp43_ = contents;
	_tmp45_ = _tmp44_ = g_strsplit (_tmp43_, "\n", 0);
	{
		gchar** line_collection = NULL;
		gint line_collection_length1 = 0;
		gint _line_collection_size_ = 0;
		gint line_it = 0;
		line_collection = _tmp45_;
		line_collection_length1 = _vala_array_length (_tmp44_);
		for (line_it = 0; line_it < _vala_array_length (_tmp44_); line_it = line_it + 1) {
			gchar* _tmp46_ = NULL;
			gchar* line = NULL;
			_tmp46_ = g_strdup (line_collection[line_it]);
			line = _tmp46_;
			{
				gchar** tokens = NULL;
				const gchar* _tmp47_ = NULL;
				gchar** _tmp48_ = NULL;
				gchar** _tmp49_ = NULL;
				gint tokens_length1 = 0;
				gint _tokens_size_ = 0;
				gchar** _tmp50_ = NULL;
				gint _tmp50__length1 = 0;
				gint width = 0;
				gchar** _tmp51_ = NULL;
				gint _tmp51__length1 = 0;
				const gchar* _tmp52_ = NULL;
				gint _tmp53_ = 0;
				gint height = 0;
				gchar** _tmp54_ = NULL;
				gint _tmp54__length1 = 0;
				const gchar* _tmp55_ = NULL;
				gint _tmp56_ = 0;
				gint n_mines = 0;
				gchar** _tmp57_ = NULL;
				gint _tmp57__length1 = 0;
				const gchar* _tmp58_ = NULL;
				gint _tmp59_ = 0;
				gint wins = 0;
				gchar** _tmp60_ = NULL;
				gint _tmp60__length1 = 0;
				const gchar* _tmp61_ = NULL;
				gint _tmp62_ = 0;
				gint loses = 0;
				gchar** _tmp63_ = NULL;
				gint _tmp63__length1 = 0;
				const gchar* _tmp64_ = NULL;
				gint _tmp65_ = 0;
				gint _tmp66_ = 0;
				gint _tmp67_ = 0;
				gint _tmp68_ = 0;
				gint _tmp69_ = 0;
				gint _tmp70_ = 0;
				StatEntry* _tmp71_ = NULL;
				_tmp47_ = line;
				_tmp49_ = _tmp48_ = g_strsplit (_tmp47_, " ", 0);
				tokens = _tmp49_;
				tokens_length1 = _vala_array_length (_tmp48_);
				_tokens_size_ = tokens_length1;
				_tmp50_ = tokens;
				_tmp50__length1 = tokens_length1;
				if (_tmp50__length1 != 5) {
					tokens = (_vala_array_free (tokens, tokens_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (line);
					continue;
				}
				_tmp51_ = tokens;
				_tmp51__length1 = tokens_length1;
				_tmp52_ = _tmp51_[0];
				_tmp53_ = atoi (_tmp52_);
				width = _tmp53_;
				_tmp54_ = tokens;
				_tmp54__length1 = tokens_length1;
				_tmp55_ = _tmp54_[1];
				_tmp56_ = atoi (_tmp55_);
				height = _tmp56_;
				_tmp57_ = tokens;
				_tmp57__length1 = tokens_length1;
				_tmp58_ = _tmp57_[2];
				_tmp59_ = atoi (_tmp58_);
				n_mines = _tmp59_;
				_tmp60_ = tokens;
				_tmp60__length1 = tokens_length1;
				_tmp61_ = _tmp60_[3];
				_tmp62_ = atoi (_tmp61_);
				wins = _tmp62_;
				_tmp63_ = tokens;
				_tmp63__length1 = tokens_length1;
				_tmp64_ = _tmp63_[4];
				_tmp65_ = atoi (_tmp64_);
				loses = _tmp65_;
				_tmp66_ = width;
				_tmp67_ = height;
				_tmp68_ = n_mines;
				_tmp69_ = wins;
				_tmp70_ = loses;
				_tmp71_ = stat_entry_new ((guint) _tmp66_, (guint) _tmp67_, (guint) _tmp68_, (guint) _tmp69_, (guint) _tmp70_);
				self->statEntries = g_list_append (self->statEntries, _tmp71_);
				tokens = (_vala_array_free (tokens, tokens_length1, (GDestroyNotify) g_free), NULL);
				_g_free0 (line);
			}
		}
		line_collection = (_vala_array_free (line_collection, line_collection_length1, (GDestroyNotify) g_free), NULL);
	}
	_g_free0 (contents);
}


static gchar* g_date_time_to_string (GDateTime* self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_date_time_format (self, "%FT%H:%M:%S%z");
	result = _tmp0_;
	return result;
}


void history_save (History* self) {
	gchar* contents = NULL;
	gchar* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
	gchar* _tmp27_ = NULL;
	GList* _tmp28_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("");
	contents = _tmp0_;
	_tmp1_ = self->entries;
	{
		GList* entry_collection = NULL;
		GList* entry_it = NULL;
		entry_collection = _tmp1_;
		for (entry_it = entry_collection; entry_it != NULL; entry_it = entry_it->next) {
			HistoryEntry* _tmp2_ = NULL;
			HistoryEntry* entry = NULL;
			_tmp2_ = _history_entry_ref0 ((HistoryEntry*) entry_it->data);
			entry = _tmp2_;
			{
				gchar* line = NULL;
				HistoryEntry* _tmp3_ = NULL;
				GDateTime* _tmp4_ = NULL;
				gchar* _tmp5_ = NULL;
				gchar* _tmp6_ = NULL;
				HistoryEntry* _tmp7_ = NULL;
				guint _tmp8_ = 0U;
				HistoryEntry* _tmp9_ = NULL;
				guint _tmp10_ = 0U;
				HistoryEntry* _tmp11_ = NULL;
				guint _tmp12_ = 0U;
				HistoryEntry* _tmp13_ = NULL;
				guint _tmp14_ = 0U;
				gchar* _tmp15_ = NULL;
				gchar* _tmp16_ = NULL;
				const gchar* _tmp17_ = NULL;
				const gchar* _tmp18_ = NULL;
				gchar* _tmp19_ = NULL;
				_tmp3_ = entry;
				_tmp4_ = _tmp3_->date;
				_tmp5_ = g_date_time_to_string (_tmp4_);
				_tmp6_ = _tmp5_;
				_tmp7_ = entry;
				_tmp8_ = _tmp7_->width;
				_tmp9_ = entry;
				_tmp10_ = _tmp9_->height;
				_tmp11_ = entry;
				_tmp12_ = _tmp11_->n_mines;
				_tmp13_ = entry;
				_tmp14_ = _tmp13_->duration;
				_tmp15_ = g_strdup_printf ("%s %u %u %u %u\n", _tmp6_, _tmp8_, _tmp10_, _tmp12_, _tmp14_);
				_tmp16_ = _tmp15_;
				_g_free0 (_tmp6_);
				line = _tmp16_;
				_tmp17_ = contents;
				_tmp18_ = line;
				_tmp19_ = g_strconcat (_tmp17_, _tmp18_, NULL);
				_g_free0 (contents);
				contents = _tmp19_;
				_g_free0 (line);
				_history_entry_unref0 (entry);
			}
		}
	}
	{
		const gchar* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
		const gchar* _tmp23_ = NULL;
		const gchar* _tmp24_ = NULL;
		_tmp20_ = self->filename;
		_tmp21_ = g_path_get_dirname (_tmp20_);
		_tmp22_ = _tmp21_;
		g_mkdir_with_parents (_tmp22_, 0775);
		_g_free0 (_tmp22_);
		_tmp23_ = self->filename;
		_tmp24_ = contents;
		g_file_set_contents (_tmp23_, _tmp24_, (gssize) (-1), &_inner_error_);
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_FILE_ERROR) {
				goto __catch4_g_file_error;
			}
			_g_free0 (contents);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally4;
	__catch4_g_file_error:
	{
		GError* e = NULL;
		GError* _tmp25_ = NULL;
		const gchar* _tmp26_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp25_ = e;
		_tmp26_ = _tmp25_->message;
		g_warning ("history.vala:147: Failed to save history: %s", _tmp26_);
		_g_error_free0 (e);
	}
	__finally4:
	if (_inner_error_ != NULL) {
		_g_free0 (contents);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp27_ = g_strdup ("");
	_g_free0 (contents);
	contents = _tmp27_;
	_tmp28_ = self->statEntries;
	{
		GList* statEntry_collection = NULL;
		GList* statEntry_it = NULL;
		statEntry_collection = _tmp28_;
		for (statEntry_it = statEntry_collection; statEntry_it != NULL; statEntry_it = statEntry_it->next) {
			StatEntry* _tmp29_ = NULL;
			StatEntry* statEntry = NULL;
			_tmp29_ = _stat_entry_ref0 ((StatEntry*) statEntry_it->data);
			statEntry = _tmp29_;
			{
				gchar* line = NULL;
				StatEntry* _tmp30_ = NULL;
				guint _tmp31_ = 0U;
				StatEntry* _tmp32_ = NULL;
				guint _tmp33_ = 0U;
				StatEntry* _tmp34_ = NULL;
				guint _tmp35_ = 0U;
				StatEntry* _tmp36_ = NULL;
				guint _tmp37_ = 0U;
				StatEntry* _tmp38_ = NULL;
				guint _tmp39_ = 0U;
				gchar* _tmp40_ = NULL;
				const gchar* _tmp41_ = NULL;
				const gchar* _tmp42_ = NULL;
				gchar* _tmp43_ = NULL;
				_tmp30_ = statEntry;
				_tmp31_ = _tmp30_->width;
				_tmp32_ = statEntry;
				_tmp33_ = _tmp32_->height;
				_tmp34_ = statEntry;
				_tmp35_ = _tmp34_->n_mines;
				_tmp36_ = statEntry;
				_tmp37_ = _tmp36_->wins;
				_tmp38_ = statEntry;
				_tmp39_ = _tmp38_->loses;
				_tmp40_ = g_strdup_printf ("%u %u %u %u %u\n", _tmp31_, _tmp33_, _tmp35_, _tmp37_, _tmp39_);
				line = _tmp40_;
				_tmp41_ = contents;
				_tmp42_ = line;
				_tmp43_ = g_strconcat (_tmp41_, _tmp42_, NULL);
				_g_free0 (contents);
				contents = _tmp43_;
				_g_free0 (line);
				_stat_entry_unref0 (statEntry);
			}
		}
	}
	{
		const gchar* _tmp44_ = NULL;
		gchar* _tmp45_ = NULL;
		gchar* _tmp46_ = NULL;
		const gchar* _tmp47_ = NULL;
		const gchar* _tmp48_ = NULL;
		_tmp44_ = self->statFileName;
		_tmp45_ = g_path_get_dirname (_tmp44_);
		_tmp46_ = _tmp45_;
		g_mkdir_with_parents (_tmp46_, 0775);
		_g_free0 (_tmp46_);
		_tmp47_ = self->statFileName;
		_tmp48_ = contents;
		g_file_set_contents (_tmp47_, _tmp48_, (gssize) (-1), &_inner_error_);
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_FILE_ERROR) {
				goto __catch5_g_file_error;
			}
			_g_free0 (contents);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally5;
	__catch5_g_file_error:
	{
		GError* e = NULL;
		GError* _tmp49_ = NULL;
		const gchar* _tmp50_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp49_ = e;
		_tmp50_ = _tmp49_->message;
		g_warning ("history.vala:164: Failed to save statistics: %s", _tmp50_);
		_g_error_free0 (e);
	}
	__finally5:
	if (_inner_error_ != NULL) {
		_g_free0 (contents);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_free0 (contents);
}


void history_reset (History* self) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	__g_list_free__history_entry_unref0_0 (self->entries);
	self->entries = NULL;
	{
		const gchar* _tmp0_ = NULL;
		_tmp0_ = self->filename;
		g_unlink (_tmp0_);
	}
	goto __finally6;
	__catch6_g_file_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_g_error_free0 (e);
	}
	__finally6:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	__g_list_free__stat_entry_unref0_0 (self->statEntries);
	self->statEntries = NULL;
	{
		const gchar* _tmp1_ = NULL;
		_tmp1_ = self->statFileName;
		g_unlink (_tmp1_);
	}
	goto __finally7;
	__catch7_g_file_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_g_error_free0 (e);
	}
	__finally7:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_ = 0L;
	gchar _tmp1_ = '\0';
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = index;
	_tmp1_ = ((gchar*) self)[_tmp0_];
	result = _tmp1_;
	return result;
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	gboolean _tmp3_ = FALSE;
	glong _tmp9_ = 0L;
	glong _tmp15_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	glong _tmp22_ = 0L;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	_tmp3_ = _tmp0_;
	if (_tmp3_) {
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		glong _tmp6_ = 0L;
		_tmp4_ = offset;
		_tmp5_ = len;
		_tmp6_ = string_strnlen ((gchar*) self, _tmp4_ + _tmp5_);
		string_length = _tmp6_;
	} else {
		gint _tmp7_ = 0;
		gint _tmp8_ = 0;
		_tmp7_ = strlen (self);
		_tmp8_ = _tmp7_;
		string_length = (glong) _tmp8_;
	}
	_tmp9_ = offset;
	if (_tmp9_ < ((glong) 0)) {
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		glong _tmp12_ = 0L;
		_tmp10_ = string_length;
		_tmp11_ = offset;
		offset = _tmp10_ + _tmp11_;
		_tmp12_ = offset;
		g_return_val_if_fail (_tmp12_ >= ((glong) 0), NULL);
	} else {
		glong _tmp13_ = 0L;
		glong _tmp14_ = 0L;
		_tmp13_ = offset;
		_tmp14_ = string_length;
		g_return_val_if_fail (_tmp13_ <= _tmp14_, NULL);
	}
	_tmp15_ = len;
	if (_tmp15_ < ((glong) 0)) {
		glong _tmp16_ = 0L;
		glong _tmp17_ = 0L;
		_tmp16_ = string_length;
		_tmp17_ = offset;
		len = _tmp16_ - _tmp17_;
	}
	_tmp18_ = offset;
	_tmp19_ = len;
	_tmp20_ = string_length;
	g_return_val_if_fail ((_tmp18_ + _tmp19_) <= _tmp20_, NULL);
	_tmp21_ = offset;
	_tmp22_ = len;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp21_, (gsize) _tmp22_);
	result = _tmp23_;
	return result;
}


static GDateTime* history_parse_date (History* self, const gchar* date) {
	GDateTime* result = NULL;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
	const gchar* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	gboolean _tmp10_ = FALSE;
	gboolean _tmp13_ = FALSE;
	gboolean _tmp16_ = FALSE;
	gboolean _tmp19_ = FALSE;
	gboolean _tmp22_ = FALSE;
	gint year = 0;
	const gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	gint _tmp26_ = 0;
	gint _tmp27_ = 0;
	gint month = 0;
	const gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	gint _tmp31_ = 0;
	gint _tmp32_ = 0;
	gint day = 0;
	const gchar* _tmp33_ = NULL;
	gchar* _tmp34_ = NULL;
	gchar* _tmp35_ = NULL;
	gint _tmp36_ = 0;
	gint _tmp37_ = 0;
	gint hour = 0;
	const gchar* _tmp38_ = NULL;
	gchar* _tmp39_ = NULL;
	gchar* _tmp40_ = NULL;
	gint _tmp41_ = 0;
	gint _tmp42_ = 0;
	gint minute = 0;
	const gchar* _tmp43_ = NULL;
	gchar* _tmp44_ = NULL;
	gchar* _tmp45_ = NULL;
	gint _tmp46_ = 0;
	gint _tmp47_ = 0;
	gint seconds = 0;
	const gchar* _tmp48_ = NULL;
	gchar* _tmp49_ = NULL;
	gchar* _tmp50_ = NULL;
	gint _tmp51_ = 0;
	gint _tmp52_ = 0;
	gchar* timezone = NULL;
	const gchar* _tmp53_ = NULL;
	gchar* _tmp54_ = NULL;
	const gchar* _tmp55_ = NULL;
	GTimeZone* _tmp56_ = NULL;
	GTimeZone* _tmp57_ = NULL;
	gint _tmp58_ = 0;
	gint _tmp59_ = 0;
	gint _tmp60_ = 0;
	gint _tmp61_ = 0;
	gint _tmp62_ = 0;
	gint _tmp63_ = 0;
	GDateTime* _tmp64_ = NULL;
	GDateTime* _tmp65_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (date != NULL, NULL);
	_tmp5_ = date;
	_tmp6_ = strlen (_tmp5_);
	_tmp7_ = _tmp6_;
	if (_tmp7_ < 19) {
		_tmp4_ = TRUE;
	} else {
		const gchar* _tmp8_ = NULL;
		gchar _tmp9_ = '\0';
		_tmp8_ = date;
		_tmp9_ = string_get (_tmp8_, (glong) 4);
		_tmp4_ = _tmp9_ != '-';
	}
	_tmp10_ = _tmp4_;
	if (_tmp10_) {
		_tmp3_ = TRUE;
	} else {
		const gchar* _tmp11_ = NULL;
		gchar _tmp12_ = '\0';
		_tmp11_ = date;
		_tmp12_ = string_get (_tmp11_, (glong) 7);
		_tmp3_ = _tmp12_ != '-';
	}
	_tmp13_ = _tmp3_;
	if (_tmp13_) {
		_tmp2_ = TRUE;
	} else {
		const gchar* _tmp14_ = NULL;
		gchar _tmp15_ = '\0';
		_tmp14_ = date;
		_tmp15_ = string_get (_tmp14_, (glong) 10);
		_tmp2_ = _tmp15_ != 'T';
	}
	_tmp16_ = _tmp2_;
	if (_tmp16_) {
		_tmp1_ = TRUE;
	} else {
		const gchar* _tmp17_ = NULL;
		gchar _tmp18_ = '\0';
		_tmp17_ = date;
		_tmp18_ = string_get (_tmp17_, (glong) 13);
		_tmp1_ = _tmp18_ != ':';
	}
	_tmp19_ = _tmp1_;
	if (_tmp19_) {
		_tmp0_ = TRUE;
	} else {
		const gchar* _tmp20_ = NULL;
		gchar _tmp21_ = '\0';
		_tmp20_ = date;
		_tmp21_ = string_get (_tmp20_, (glong) 16);
		_tmp0_ = _tmp21_ != ':';
	}
	_tmp22_ = _tmp0_;
	if (_tmp22_) {
		result = NULL;
		return result;
	}
	_tmp23_ = date;
	_tmp24_ = string_substring (_tmp23_, (glong) 0, (glong) 4);
	_tmp25_ = _tmp24_;
	_tmp26_ = atoi (_tmp25_);
	_tmp27_ = _tmp26_;
	_g_free0 (_tmp25_);
	year = _tmp27_;
	_tmp28_ = date;
	_tmp29_ = string_substring (_tmp28_, (glong) 5, (glong) 2);
	_tmp30_ = _tmp29_;
	_tmp31_ = atoi (_tmp30_);
	_tmp32_ = _tmp31_;
	_g_free0 (_tmp30_);
	month = _tmp32_;
	_tmp33_ = date;
	_tmp34_ = string_substring (_tmp33_, (glong) 8, (glong) 2);
	_tmp35_ = _tmp34_;
	_tmp36_ = atoi (_tmp35_);
	_tmp37_ = _tmp36_;
	_g_free0 (_tmp35_);
	day = _tmp37_;
	_tmp38_ = date;
	_tmp39_ = string_substring (_tmp38_, (glong) 11, (glong) 2);
	_tmp40_ = _tmp39_;
	_tmp41_ = atoi (_tmp40_);
	_tmp42_ = _tmp41_;
	_g_free0 (_tmp40_);
	hour = _tmp42_;
	_tmp43_ = date;
	_tmp44_ = string_substring (_tmp43_, (glong) 14, (glong) 2);
	_tmp45_ = _tmp44_;
	_tmp46_ = atoi (_tmp45_);
	_tmp47_ = _tmp46_;
	_g_free0 (_tmp45_);
	minute = _tmp47_;
	_tmp48_ = date;
	_tmp49_ = string_substring (_tmp48_, (glong) 17, (glong) 2);
	_tmp50_ = _tmp49_;
	_tmp51_ = atoi (_tmp50_);
	_tmp52_ = _tmp51_;
	_g_free0 (_tmp50_);
	seconds = _tmp52_;
	_tmp53_ = date;
	_tmp54_ = string_substring (_tmp53_, (glong) 19, (glong) (-1));
	timezone = _tmp54_;
	_tmp55_ = timezone;
	_tmp56_ = g_time_zone_new (_tmp55_);
	_tmp57_ = _tmp56_;
	_tmp58_ = year;
	_tmp59_ = month;
	_tmp60_ = day;
	_tmp61_ = hour;
	_tmp62_ = minute;
	_tmp63_ = seconds;
	_tmp64_ = g_date_time_new (_tmp57_, _tmp58_, _tmp59_, _tmp60_, _tmp61_, _tmp62_, (gdouble) _tmp63_);
	_tmp65_ = _tmp64_;
	_g_time_zone_unref0 (_tmp57_);
	result = _tmp65_;
	_g_free0 (timezone);
	return result;
}


static void g_cclosure_user_marshal_VOID__HISTORY_ENTRY (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__HISTORY_ENTRY) (gpointer data1, gpointer arg_1, gpointer data2);
	register GMarshalFunc_VOID__HISTORY_ENTRY callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 2);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__HISTORY_ENTRY) (marshal_data ? marshal_data : cc->callback);
	callback (data1, value_get_history_entry (param_values + 1), data2);
}


static void value_history_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_history_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		history_unref (value->data[0].v_pointer);
	}
}


static void value_history_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = history_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_history_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_history_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		History* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = history_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_history_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	History** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = history_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_history (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecHistory* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_HISTORY), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_history (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_HISTORY), NULL);
	return value->data[0].v_pointer;
}


void value_set_history (GValue* value, gpointer v_object) {
	History* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_HISTORY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_HISTORY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		history_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		history_unref (old);
	}
}


void value_take_history (GValue* value, gpointer v_object) {
	History* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_HISTORY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_HISTORY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		history_unref (old);
	}
}


static void history_class_init (HistoryClass * klass) {
	history_parent_class = g_type_class_peek_parent (klass);
	HISTORY_CLASS (klass)->finalize = history_finalize;
	g_signal_new ("entry_added", TYPE_HISTORY, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__HISTORY_ENTRY, G_TYPE_NONE, 1, TYPE_HISTORY_ENTRY);
}


static void history_instance_init (History * self) {
	self->ref_count = 1;
}


static void history_finalize (History* obj) {
	History * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_HISTORY, History);
	_g_free0 (self->filename);
	_g_free0 (self->statFileName);
	__g_list_free__history_entry_unref0_0 (self->entries);
	__g_list_free__stat_entry_unref0_0 (self->statEntries);
}


GType history_get_type (void) {
	static volatile gsize history_type_id__volatile = 0;
	if (g_once_init_enter (&history_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_history_init, value_history_free_value, value_history_copy_value, value_history_peek_pointer, "p", value_history_collect_value, "p", value_history_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (HistoryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) history_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (History), 0, (GInstanceInitFunc) history_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType history_type_id;
		history_type_id = g_type_register_fundamental (g_type_fundamental_next (), "History", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&history_type_id__volatile, history_type_id);
	}
	return history_type_id__volatile;
}


gpointer history_ref (gpointer instance) {
	History* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void history_unref (gpointer instance) {
	History* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		HISTORY_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static gpointer _g_date_time_ref0 (gpointer self) {
	return self ? g_date_time_ref (self) : NULL;
}


HistoryEntry* history_entry_construct (GType object_type, GDateTime* date, guint width, guint height, guint n_mines, guint duration) {
	HistoryEntry* self = NULL;
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
	guint _tmp3_ = 0U;
	guint _tmp4_ = 0U;
	guint _tmp5_ = 0U;
	g_return_val_if_fail (date != NULL, NULL);
	self = (HistoryEntry*) g_type_create_instance (object_type);
	_tmp0_ = date;
	_tmp1_ = _g_date_time_ref0 (_tmp0_);
	_g_date_time_unref0 (self->date);
	self->date = _tmp1_;
	_tmp2_ = width;
	self->width = _tmp2_;
	_tmp3_ = height;
	self->height = _tmp3_;
	_tmp4_ = n_mines;
	self->n_mines = _tmp4_;
	_tmp5_ = duration;
	self->duration = _tmp5_;
	return self;
}


HistoryEntry* history_entry_new (GDateTime* date, guint width, guint height, guint n_mines, guint duration) {
	return history_entry_construct (TYPE_HISTORY_ENTRY, date, width, height, n_mines, duration);
}


static void value_history_entry_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_history_entry_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		history_entry_unref (value->data[0].v_pointer);
	}
}


static void value_history_entry_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = history_entry_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_history_entry_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_history_entry_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		HistoryEntry* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = history_entry_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_history_entry_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	HistoryEntry** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = history_entry_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_history_entry (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecHistoryEntry* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_HISTORY_ENTRY), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_history_entry (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_HISTORY_ENTRY), NULL);
	return value->data[0].v_pointer;
}


void value_set_history_entry (GValue* value, gpointer v_object) {
	HistoryEntry* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_HISTORY_ENTRY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_HISTORY_ENTRY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		history_entry_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		history_entry_unref (old);
	}
}


void value_take_history_entry (GValue* value, gpointer v_object) {
	HistoryEntry* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_HISTORY_ENTRY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_HISTORY_ENTRY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		history_entry_unref (old);
	}
}


static void history_entry_class_init (HistoryEntryClass * klass) {
	history_entry_parent_class = g_type_class_peek_parent (klass);
	HISTORY_ENTRY_CLASS (klass)->finalize = history_entry_finalize;
}


static void history_entry_instance_init (HistoryEntry * self) {
	self->ref_count = 1;
}


static void history_entry_finalize (HistoryEntry* obj) {
	HistoryEntry * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_HISTORY_ENTRY, HistoryEntry);
	_g_date_time_unref0 (self->date);
}


GType history_entry_get_type (void) {
	static volatile gsize history_entry_type_id__volatile = 0;
	if (g_once_init_enter (&history_entry_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_history_entry_init, value_history_entry_free_value, value_history_entry_copy_value, value_history_entry_peek_pointer, "p", value_history_entry_collect_value, "p", value_history_entry_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (HistoryEntryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) history_entry_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HistoryEntry), 0, (GInstanceInitFunc) history_entry_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType history_entry_type_id;
		history_entry_type_id = g_type_register_fundamental (g_type_fundamental_next (), "HistoryEntry", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&history_entry_type_id__volatile, history_entry_type_id);
	}
	return history_entry_type_id__volatile;
}


gpointer history_entry_ref (gpointer instance) {
	HistoryEntry* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void history_entry_unref (gpointer instance) {
	HistoryEntry* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		HISTORY_ENTRY_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


StatEntry* stat_entry_construct (GType object_type, guint width, guint height, guint n_mines, guint wins, guint loses) {
	StatEntry* self = NULL;
	guint _tmp0_ = 0U;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
	guint _tmp3_ = 0U;
	guint _tmp4_ = 0U;
	self = (StatEntry*) g_type_create_instance (object_type);
	_tmp0_ = width;
	self->width = _tmp0_;
	_tmp1_ = height;
	self->height = _tmp1_;
	_tmp2_ = n_mines;
	self->n_mines = _tmp2_;
	_tmp3_ = wins;
	self->wins = _tmp3_;
	_tmp4_ = loses;
	self->loses = _tmp4_;
	return self;
}


StatEntry* stat_entry_new (guint width, guint height, guint n_mines, guint wins, guint loses) {
	return stat_entry_construct (TYPE_STAT_ENTRY, width, height, n_mines, wins, loses);
}


static void value_stat_entry_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_stat_entry_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		stat_entry_unref (value->data[0].v_pointer);
	}
}


static void value_stat_entry_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = stat_entry_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_stat_entry_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_stat_entry_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		StatEntry* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = stat_entry_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_stat_entry_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	StatEntry** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = stat_entry_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_stat_entry (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecStatEntry* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_STAT_ENTRY), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_stat_entry (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_STAT_ENTRY), NULL);
	return value->data[0].v_pointer;
}


void value_set_stat_entry (GValue* value, gpointer v_object) {
	StatEntry* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_STAT_ENTRY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_STAT_ENTRY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		stat_entry_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		stat_entry_unref (old);
	}
}


void value_take_stat_entry (GValue* value, gpointer v_object) {
	StatEntry* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_STAT_ENTRY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_STAT_ENTRY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		stat_entry_unref (old);
	}
}


static void stat_entry_class_init (StatEntryClass * klass) {
	stat_entry_parent_class = g_type_class_peek_parent (klass);
	STAT_ENTRY_CLASS (klass)->finalize = stat_entry_finalize;
}


static void stat_entry_instance_init (StatEntry * self) {
	self->ref_count = 1;
}


static void stat_entry_finalize (StatEntry* obj) {
	StatEntry * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_STAT_ENTRY, StatEntry);
}


GType stat_entry_get_type (void) {
	static volatile gsize stat_entry_type_id__volatile = 0;
	if (g_once_init_enter (&stat_entry_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_stat_entry_init, value_stat_entry_free_value, value_stat_entry_copy_value, value_stat_entry_peek_pointer, "p", value_stat_entry_collect_value, "p", value_stat_entry_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (StatEntryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) stat_entry_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StatEntry), 0, (GInstanceInitFunc) stat_entry_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType stat_entry_type_id;
		stat_entry_type_id = g_type_register_fundamental (g_type_fundamental_next (), "StatEntry", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&stat_entry_type_id__volatile, stat_entry_type_id);
	}
	return stat_entry_type_id__volatile;
}


gpointer stat_entry_ref (gpointer instance) {
	StatEntry* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void stat_entry_unref (gpointer instance) {
	StatEntry* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		STAT_ENTRY_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



